import { inject } from 'vue';
import type { Rgba } from '@/core/diagram_types.ts';
import { SETTINGS_KEY } from '@/composables/use_settings.ts';

export interface ColorTheme {
    id: string;
    label_key: string;
    vars: Record<string, string>;
    /** type → Rgba, 供图的 ColorSpec 解析使用。 */
    palette: Record<string, Rgba>;
}

export const themes: ColorTheme[] = [
    {
        id: 'default',
        label_key: 'theme.default',
        vars: {
            '--color-text': '#000',
            '--color-text-secondary': '#888',
            '--color-text-muted': '#999',
            '--color-primary': '#90f',
            '--color-primary-hover': '#c8f',
            '--color-primary-active': '#60a',
            '--color-primary-bg': '#daf',
            '--color-category': '#f90',
            '--color-category-hover': '#fd9',
            '--color-category-bg': '#feb',
            '--color-accent': '#06c',
            '--color-accent-hover': '#08e',
            '--color-accent-active': '#048',
            '--color-accent-bg': '#cdf',
            '--color-danger': '#c00',
            '--color-success': '#080',
            '--color-border': '#999',
            '--color-border-light': '#ddd',
            '--color-border-subtle': '#eee',
            '--color-bg': '#fff',
            '--color-page-bg': '#fff',
            '--color-bg-secondary': '#f8f8f8',
            '--color-bg-hover': '#e8e8e8',
            '--color-bg-active': '#d0d0d0',
            '--color-tree-hover': '#cff',
            '--color-tree-analyzed': '#eee',
            '--color-tree-analyzed-hover': '#bee',
            '--color-selected': '#cfc',
            '--color-selected-hover': '#afa',
            '--color-shadow': 'rgba(0,0,0,0.15)',
            '--color-overlay': 'rgba(0,0,0,0.35)',
            '--color-editor-keyword': '#7c3aed',
            '--color-editor-literal': '#b42318',
            '--color-editor-number': '#0550ae',
            '--color-editor-string': '#116329',
            '--color-editor-comment': '#6e7781',
        },
        palette: {
            text: { r: 0, g: 0, b: 0 },
            background: { r: 255, g: 255, b: 255 },
            red: { r: 255, g: 0, b: 0 },
            gray: { r: 200, g: 200, b: 200 },
        },
    },
    {
        id: 'dark',
        label_key: 'theme.dark',
        vars: {
            '--color-text': '#cdd6f4',
            '--color-text-secondary': '#6c7086',
            '--color-text-muted': '#6c7086',
            '--color-primary': '#c8a0ff',
            '--color-primary-hover': '#b388ff',
            '--color-primary-active': '#b388ff',
            '--color-primary-bg': '#3b2a5e',
            '--color-category': '#ffb347',
            '--color-category-hover': '#ffa01a',
            '--color-category-bg': '#4a3520',
            '--color-accent': '#89b4fa',
            '--color-accent-hover': '#9fc4ff',
            '--color-accent-active': '#6a9fd8',
            '--color-accent-bg': '#2a3a5e',
            '--color-danger': '#f38ba8',
            '--color-success': '#a6e3a1',
            '--color-border': '#585b70',
            '--color-border-light': '#45475a',
            '--color-border-subtle': '#313244',
            '--color-bg': '#1e1e2e',
            '--color-page-bg': '#1e1e2e',
            '--color-bg-secondary': '#2a2a3d',
            '--color-bg-hover': '#35354a',
            '--color-bg-active': '#404060',
            '--color-tree-hover': '#252540',
            '--color-tree-analyzed': '#272738',
            '--color-tree-analyzed-hover': '#2a3840',
            '--color-selected': '#2a4a2a',
            '--color-selected-hover': '#3a6a3a',
            '--color-shadow': 'rgba(0,0,0,0.4)',
            '--color-overlay': 'rgba(0,0,0,0.6)',
            '--color-editor-keyword': '#c586c0',
            '--color-editor-literal': '#b5cea8',
            '--color-editor-number': '#b5cea8',
            '--color-editor-string': '#ce9178',
            '--color-editor-comment': '#6a9955',
        },
        palette: {
            text: { r: 205, g: 214, b: 244 },
            background: { r: 30, g: 30, b: 46 },
            red: { r: 255, g: 107, b: 107 },
            gray: { r: 110, g: 115, b: 134 },
        },
    },
    {
        id: 'source-light',
        label_key: 'theme.source-light',
        vars: {
            '--color-text': '#1e1e1e',
            '--color-text-secondary': '#667085',
            '--color-text-muted': '#98a2b3',
            '--color-primary': '#2563eb',
            '--color-primary-hover': '#1d4ed8',
            '--color-primary-active': '#1e40af',
            '--color-primary-bg': '#dbeafe',
            '--color-category': '#d97706',
            '--color-category-hover': '#b45309',
            '--color-category-bg': '#fef3c7',
            '--color-accent': '#2563eb',
            '--color-accent-hover': '#1d4ed8',
            '--color-accent-active': '#1e40af',
            '--color-accent-bg': '#dbeafe',
            '--color-danger': '#b91c1c',
            '--color-success': '#166534',
            '--color-border': '#d0d5dd',
            '--color-border-light': '#e5e7eb',
            '--color-border-subtle': '#eef2f6',
            '--color-bg': '#fff',
            '--color-page-bg': '#f8f9fa',
            '--color-bg-secondary': '#f8f9fa',
            '--color-bg-hover': '#f0f1f3',
            '--color-bg-active': '#e4e5e7',
            '--color-tree-hover': '#dbeafe',
            '--color-tree-analyzed': '#f3f4f6',
            '--color-tree-analyzed-hover': '#dbeafe',
            '--color-selected': '#dcfce7',
            '--color-selected-hover': '#bbf7d0',
            '--color-shadow': 'rgba(17,24,39,0.18)',
            '--color-overlay': 'rgba(0,0,0,0.35)',
            '--color-editor-keyword': '#7c3aed',
            '--color-editor-literal': '#b42318',
            '--color-editor-number': '#0550ae',
            '--color-editor-string': '#116329',
            '--color-editor-comment': '#6e7781',
        },
        palette: {
            text: { r: 30, g: 30, b: 30 },
            background: { r: 255, g: 255, b: 255 },
            red: { r: 185, g: 28, b: 28 },
            gray: { r: 102, g: 112, b: 133 },
        },
    },
    {
        id: 'source-dark',
        label_key: 'theme.source-dark',
        vars: {
            '--color-text': '#e0e0e0',
            '--color-text-secondary': '#aeb3bb',
            '--color-text-muted': '#8b909a',
            '--color-primary': '#5b7fcf',
            '--color-primary-hover': '#6f91dd',
            '--color-primary-active': '#4a6fb0',
            '--color-primary-bg': '#25334a',
            '--color-category': '#f59e0b',
            '--color-category-hover': '#fbbf24',
            '--color-category-bg': '#4a3615',
            '--color-accent': '#5b7fcf',
            '--color-accent-hover': '#6f91dd',
            '--color-accent-active': '#4a6fb0',
            '--color-accent-bg': '#25334a',
            '--color-danger': '#fca5a5',
            '--color-success': '#bbf7d0',
            '--color-border': '#4a4a4a',
            '--color-border-light': '#41444b',
            '--color-border-subtle': '#34373c',
            '--color-bg': '#1a1a1a',
            '--color-page-bg': '#111111',
            '--color-bg-secondary': '#2d2d2d',
            '--color-bg-hover': '#3a3a3a',
            '--color-bg-active': '#4a4a4a',
            '--color-tree-hover': '#25334a',
            '--color-tree-analyzed': '#292c31',
            '--color-tree-analyzed-hover': '#25334a',
            '--color-selected': '#1f3b2b',
            '--color-selected-hover': '#285438',
            '--color-shadow': 'rgba(0,0,0,0.5)',
            '--color-overlay': 'rgba(0,0,0,0.7)',
            '--color-editor-keyword': '#c586c0',
            '--color-editor-literal': '#b5cea8',
            '--color-editor-number': '#b5cea8',
            '--color-editor-string': '#ce9178',
            '--color-editor-comment': '#6a9955',
        },
        palette: {
            text: { r: 224, g: 224, b: 224 },
            background: { r: 26, g: 26, b: 26 },
            red: { r: 252, g: 165, b: 165 },
            gray: { r: 139, g: 144, b: 154 },
        },
    },
    {
        id: 'high-contrast',
        label_key: 'theme.high-contrast',
        vars: {
            '--color-text': '#000',
            '--color-text-secondary': '#555',
            '--color-text-muted': '#666',
            '--color-primary': '#50f',
            '--color-primary-hover': '#70f',
            '--color-primary-active': '#50f',
            '--color-primary-bg': '#d0b0ff',
            '--color-category': '#e65c00',
            '--color-category-hover': '#ff7b00',
            '--color-category-bg': '#ffe0b0',
            '--color-accent': '#06c',
            '--color-accent-hover': '#07e',
            '--color-accent-active': '#035',
            '--color-accent-bg': '#cdf',
            '--color-danger': '#c00',
            '--color-success': '#080',
            '--color-border': '#000',
            '--color-border-light': '#000',
            '--color-border-subtle': '#ccc',
            '--color-bg': '#fff',
            '--color-page-bg': '#fff',
            '--color-bg-secondary': '#e8e8e8',
            '--color-bg-hover': '#d0d0d0',
            '--color-bg-active': '#bbb',
            '--color-tree-hover': '#cff',
            '--color-tree-analyzed': '#eee',
            '--color-tree-analyzed-hover': '#bee',
            '--color-selected': '#cfc',
            '--color-selected-hover': '#afa',
            '--color-shadow': 'rgba(0,0,0,0.3)',
            '--color-overlay': 'rgba(0,0,0,0.5)',
            '--color-editor-keyword': '#7c3aed',
            '--color-editor-literal': '#b42318',
            '--color-editor-number': '#0550ae',
            '--color-editor-string': '#116329',
            '--color-editor-comment': '#6e7781',
        },
        palette: {
            text: { r: 0, g: 0, b: 0 },
            background: { r: 255, g: 255, b: 255 },
            red: { r: 255, g: 0, b: 0 },
            gray: { r: 200, g: 200, b: 200 },
        },
    },
    {
        id: 'high-contrast-dark',
        label_key: 'theme.high-contrast-dark',
        vars: {
            '--color-text': '#fff',
            '--color-text-secondary': '#bbb',
            '--color-text-muted': '#888',
            '--color-primary': '#b366ff',
            '--color-primary-hover': '#d499ff',
            '--color-primary-active': '#fff',
            '--color-primary-bg': '#4a0072',
            '--color-category': '#ff8c00',
            '--color-category-hover': '#ffaa33',
            '--color-category-bg': '#5c3300',
            '--color-accent': '#66b3ff',
            '--color-accent-hover': '#88ccff',
            '--color-accent-active': '#4499ee',
            '--color-accent-bg': '#1a3a5e',
            '--color-danger': '#ff4444',
            '--color-success': '#44cc44',
            '--color-border': '#666',
            '--color-border-light': '#555',
            '--color-border-subtle': '#333',
            '--color-bg': '#0d0d0d',
            '--color-page-bg': '#0d0d0d',
            '--color-bg-secondary': '#1a1a1a',
            '--color-bg-hover': '#2a2a2a',
            '--color-bg-active': '#3a3a3a',
            '--color-tree-hover': '#1a2a3a',
            '--color-tree-analyzed': '#1a1a2a',
            '--color-tree-analyzed-hover': '#1a2a3a',
            '--color-selected': '#1a3a1a',
            '--color-selected-hover': '#2a4a2a',
            '--color-shadow': 'rgba(0,0,0,0.5)',
            '--color-overlay': 'rgba(0,0,0,0.7)',
            '--color-editor-keyword': '#c586c0',
            '--color-editor-literal': '#b5cea8',
            '--color-editor-number': '#b5cea8',
            '--color-editor-string': '#ce9178',
            '--color-editor-comment': '#6a9955',
        },
        palette: {
            text: { r: 255, g: 255, b: 255 },
            background: { r: 13, g: 13, b: 13 },
            red: { r: 255, g: 68, b: 68 },
            gray: { r: 170, g: 170, b: 170 },
        },
    },
];

/** 按主题 id 取 palette (未知 id 回退默认主题)。 */
export function theme_palette(theme_id: string | undefined): Record<string, Rgba> {
    const theme = themes.find((t) => t.id === theme_id) ?? themes[0];
    return theme.palette;
}

export function apply_color_theme(theme_id: string): void {
    const theme = themes.find((t) => t.id === theme_id) ?? themes[0];
    const root = document.documentElement;
    for (const [key, value] of Object.entries(theme.vars)) {
        root.style.setProperty(key, value);
    }
}

export function use_color_theme() {
    const settings = inject(SETTINGS_KEY)!;

    function init_theme() {
        apply_color_theme(settings.color_scheme ?? 'default');
    }

    function set_theme(id: string) {
        settings.color_scheme = id;
        apply_color_theme(id);
    }

    return { init_theme, set_theme, themes };
}
